# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'M_0.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 400)
        Dialog.setMinimumSize(QtCore.QSize(500, 400))
        Dialog.setMaximumSize(QtCore.QSize(1000, 800))
        Dialog.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.title_A = QtWidgets.QLabel(Dialog)
        self.title_A.setGeometry(QtCore.QRect(160, 100, 171, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.title_A.setFont(font)
        self.title_A.setObjectName("title_A")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(110, 120, 271, 201))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.title_A_2 = QtWidgets.QLabel(Dialog)
        self.title_A_2.setGeometry(QtCore.QRect(10, 350, 151, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.title_A_2.setFont(font)
        self.title_A_2.setObjectName("title_A_2")
        self.scalar = QtWidgets.QLineEdit(Dialog)
        self.scalar.setGeometry(QtCore.QRect(170, 350, 121, 20))
        self.scalar.setObjectName("scalar")
        self.columns = QtWidgets.QLineEdit(Dialog)
        self.columns.setGeometry(QtCore.QRect(160, 40, 121, 20))
        self.columns.setObjectName("columns")
        self.title_A_3 = QtWidgets.QLabel(Dialog)
        self.title_A_3.setGeometry(QtCore.QRect(10, 10, 271, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.title_A_3.setFont(font)
        self.title_A_3.setObjectName("title_A_3")
        self.title_A_4 = QtWidgets.QLabel(Dialog)
        self.title_A_4.setGeometry(QtCore.QRect(10, 40, 141, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.title_A_4.setFont(font)
        self.title_A_4.setObjectName("title_A_4")
        self.title_A_5 = QtWidgets.QLabel(Dialog)
        self.title_A_5.setGeometry(QtCore.QRect(10, 60, 111, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.title_A_5.setFont(font)
        self.title_A_5.setObjectName("title_A_5")
        self.lines = QtWidgets.QLineEdit(Dialog)
        self.lines.setGeometry(QtCore.QRect(160, 60, 121, 20))
        self.lines.setObjectName("lines")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(310, 40, 131, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 340, 131, 41))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Ошибка"))
        self.title_A.setText(_translate("Dialog", "Заполните матрицу A:"))
        self.title_A_2.setText(_translate("Dialog", "Введите скаляр b:"))
        self.title_A_3.setText(_translate("Dialog", "Введите размерность матрицы A:"))
        self.title_A_4.setText(_translate("Dialog", "Кол-во столбцов:"))
        self.title_A_5.setText(_translate("Dialog", "Кол-во строк:"))
        self.pushButton.setText(_translate("Dialog", "Заполнить матрицу"))
        self.pushButton_2.setText(_translate("Dialog", "Выполнить операцию"))
