# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setMinimumSize(QtCore.QSize(400, 300))
        Dialog.setMaximumSize(QtCore.QSize(400, 300))
        Dialog.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(80, 70, 241, 22))
        self.comboBox.setObjectName("comboBox")
        self.title_A_2 = QtWidgets.QLabel(Dialog)
        self.title_A_2.setGeometry(QtCore.QRect(50, 30, 311, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.title_A_2.setFont(font)
        self.title_A_2.setObjectName("title_A_2")
        self.generate_and_calculate = QtWidgets.QPushButton(Dialog)
        self.generate_and_calculate.setEnabled(True)
        self.generate_and_calculate.setGeometry(QtCore.QRect(140, 150, 120, 80))
        self.generate_and_calculate.setMinimumSize(QtCore.QSize(120, 80))
        self.generate_and_calculate.setMaximumSize(QtCore.QSize(120, 80))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.generate_and_calculate.setFont(font)
        self.generate_and_calculate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.generate_and_calculate.setStyleSheet("background-color: #00dd00;\n"
"color: #000000;")
        self.generate_and_calculate.setObjectName("generate_and_calculate")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Выбор операции"))
        self.title_A_2.setText(_translate("Dialog", "Выберите одну из доступных операций:"))
        self.generate_and_calculate.setText(_translate("Dialog", "ОК"))
