# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(400, 300)
        MainWindow.setMinimumSize(QtCore.QSize(400, 300))
        MainWindow.setMaximumSize(QtCore.QSize(400, 300))
        MainWindow.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.generate_and_calculate = QtWidgets.QPushButton(self.centralwidget)
        self.generate_and_calculate.setEnabled(True)
        self.generate_and_calculate.setGeometry(QtCore.QRect(140, 150, 120, 80))
        self.generate_and_calculate.setMinimumSize(QtCore.QSize(120, 80))
        self.generate_and_calculate.setMaximumSize(QtCore.QSize(120, 80))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.generate_and_calculate.setFont(font)
        self.generate_and_calculate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.generate_and_calculate.setStyleSheet("background-color: #00dd00;\n"
"color: #000000;")
        self.generate_and_calculate.setObjectName("generate_and_calculate")
        self.title_A = QtWidgets.QLabel(self.centralwidget)
        self.title_A.setGeometry(QtCore.QRect(70, 20, 261, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.title_A.setFont(font)
        self.title_A.setObjectName("title_A")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(80, 90, 241, 22))
        self.comboBox.setObjectName("comboBox")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Выбор операции"))
        self.generate_and_calculate.setText(_translate("MainWindow", "ОК"))
        self.title_A.setText(_translate("MainWindow", "<html><head/><body><p>Выберите с каким блоком будет </p><p align=\"center\">выполняться операция:</p></body></html>"))
